import type { Metadata } from "next";
import { AuthProvider, QueryProvider } from "@/libs";
import { Inter } from "next/font/google";
import { FC, PropsWithChildren, ReactElement } from "react";
import "@/styles/global.css";
import { Maintenance } from "@/modules";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "NextJS 13 Boilerplate",
  description: "Generated by create next app",
};

const isMaintenance = process.env.NEXT_PUBLIC_MAINTENANCE_MODE === "1";

const RootLayout: FC<PropsWithChildren> = ({ children }): ReactElement => {
  return (
    <html lang="en">
      <body className={inter.className}>
        {isMaintenance ? (
          <Maintenance />
        ) : (
          <AuthProvider>
            <QueryProvider>{children}</QueryProvider>
          </AuthProvider>
        )}
      </body>
    </html>
  );
};

export default RootLayout;
