import { QueryProvider } from "@/libs";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { FC, PropsWithChildren, ReactElement } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "NextJS 13 Boilerplate",
  description: "Generated by create next app",
};

const RootLayout: FC<PropsWithChildren> = ({ children }): ReactElement => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryProvider>{children}</QueryProvider>
      </body>
    </html>
  );
};

export default RootLayout;
